services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: leadinfo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "8081:8080"
    environment:
      APP_DEBUG: "true"
      APP_ORIGIN: "http://localhost:5173"
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: leadinfo
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db
    command: >
      bash -lc "curl -sS https://getcomposer.org/installer | php &&
                php composer.phar install &&
                php -S 0.0.0.0:8080 -t public"
volumes:
  db_data: